# ----------------------------- DESCRIPTION -----------------------------
# Slightly skinned down version of the official KASM Ubuntu Noble workspace dockerfile.
# Installs Ubuntu, provides Docker-In-A-Docker and gives root access to OS.
# - Optional lint target to enforce installer standards
#
# ----------------------------- INSTRUCTIONS -----------------------------
# Sanity Checks and testing:
# 1 - ALWAYS Run Lint to make sure you aren't shooting yourself in the foot!
#     - docker build --target lint -f dockerfile-squirrelworksllc-ubuntu-noble-dind .
# If Lint is fine then you can proceed to building the actual image (build without target)!
#
# In Dockerfile
# 1 - Decide if you are using the "1.18.0" or "develop" branch.
# 2 - When you build the dockerfile, be sure you specify the correct branch: squirrelworksllc/ubuntu-noble-dind:BRANCH-GOES-HERE
#
# In Workspace file following modification/update of THIS file:
# 1 - recalculate the docker size via commandline with one of the following (depending on docker tag used)
#     production: "docker inspect -f "{{ .Size }}" squirrelworksllc/ubuntu-noble-dind:1.18.0"
#     development: "docker inspect -f "{{ .Size }}" squirrelworksllc/ubuntu-noble-dind:develop"
# 2 - adjust the variable "uncompressed_size_mb"
# ----------------------------------------------------------------------

# DEV NOTE: The tag can change as Kasm changes, use stable and not rolling.
ARG BASE_TAG="1.18.0"
# DEV NOTE: IF an Ubuntu version changes you should be making a new dockerfile!
ARG BASE_IMAGE="core-ubuntu-noble"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME=/home/kasm-default-profile
ENV STARTUPDIR=/dockerstartup
WORKDIR $HOME

### Envrionment config
ENV DEBUG=false \
    DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/ubuntu/install/tools/install_tools.sh \
                  /ubuntu/install/dind/install_dind.sh \
                  /ubuntu/install/chrome/install_chrome.sh \
                  /ubuntu/install/vs_code/install_vs_code.sh \
                  /ubuntu/install/common/01_cleanup.sh"

# Startup Scripts specific to DIND
COPY ./src/ubuntu/install/dind/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh
COPY ./src/ubuntu/install/dind/dockerd.conf /etc/supervisor/conf.d/

# Copy install scripts
COPY ./src/ $INST_DIR

# Run installations
RUN set -eux; \
    apt-get update; \
    for SCRIPT in ${INST_SCRIPTS}; do \
      echo ">>> Running ${SCRIPT}"; \
      bash "${INST_DIR}${SCRIPT}" || { echo "FAILED: ${SCRIPT}"; exit 1; }; \
    done; \
    "${STARTUPDIR}/set_user_permission.sh" "${HOME}"; \
    rm -f /etc/X11/xinit/Xclients; \
    chown 1000:0 "${HOME}"; \
    mkdir -p /home/kasm-user; \
    chown -R 1000:0 /home/kasm-user; \
    rm -rf "${INST_DIR}"

# Userspace Runtime
ENV HOME=/home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]