WIP - NOT WORKING
# ----------------------------- DESCRIPTION -----------------------------
# Custom script to create a Bitcurator5 Docker. Bitcurator 5's newest version supports up to Ubuntu Noble so
# this script will base the "root OS" off of the kasmweb ubuntu noble "Docker In a Docker" desktop.
#
# ----------------------------- INSTRUCTIONS -----------------------------
# Sanity Checks and testing:
# 1 - ALWAYS Run Lint to make sure you aren't shooting yourself in the foot!
#     - docker build --target lint -f dockerfile-squirrelworksllc-bitcurator5 .
# If Lint is fine then you can proceed to building the actual image (build without target)!
#
# In Dockerfile
# 1 - Decide if you are using the "1.18.0" or "develop" branch.
# 2 - When you build the dockerfile, be sure you specify the correct branch: squirrelworksllc/ubuntu-noble-dind:BRANCH-GOES-HERE
#
# In Workspace file following modification/update of THIS file:
# 1 - recalculate the docker size via commandline with one of the following (depending on docker tag used):
#     production: "docker inspect -f "{{ .Size }}" squirrelworksllc/bitcurator5:latest"
#     development: "docker inspect -f "{{ .Size }}" squirrelworksllc/bitcurator5:develop"
# 2 - adjust the variable "uncompressed_size_mb"
# ----------------------------------------------------------------------

# DEV NOTE: The tag can change as Kasm changes
ARG BASE_TAG="1.18.0-rolling-weekly"
ARG BASE_IMAGE="ubuntu-noble-dind"

# ----------------------------- LINT TARGET -----------------------------
FROM kasmweb/${BASE_IMAGE}:${BASE_TAG} AS lint
USER root
WORKDIR /lint

COPY ./tools/lint_installers.sh /lint/tools/lint_installers.sh
COPY ./src/ /lint/src/

RUN chmod +x /lint/tools/lint_installers.sh && \
    /lint/tools/lint_installers.sh


# ----------------------------- RUNTIME IMAGE ---------------------------
FROM kasmweb/${BASE_IMAGE}:${BASE_TAG}
USER root

ENV HOME=/home/kasm-default-profile
ENV STARTUPDIR=/dockerstartup
WORKDIR ${HOME}

### Environment config
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=${STARTUPDIR}/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=${STARTUPDIR}/install \
    INST_SCRIPTS="/ubuntu/install/tools/install_tools.sh \
                  /ubuntu/install/bitcurator/install_bitcurator5.sh \
                  /ubuntu/install/common/01_cleanup.sh"

# Copy install scripts
COPY ./src/ ${INST_DIR}

# Run installations (one apt-get update here; scripts use apt_update_if_needed)
RUN set -eux; \
    apt-get update; \
    for SCRIPT in ${INST_SCRIPTS}; do \
      echo ">>> Running ${SCRIPT}"; \
      bash "${INST_DIR}${SCRIPT}"; \
    done; \
    ${STARTUPDIR}/set_user_permission.sh "${HOME}"; \
    rm -f /etc/X11/xinit/Xclients; \
    chown 1000:0 "${HOME}"; \
    mkdir -p /home/kasm-user; \
    chown -R 1000:0 /home/kasm-user; \
    rm -rf "${INST_DIR}"

# Userspace Runtime
ENV HOME=/home/kasm-user
WORKDIR ${HOME}
USER 1000

CMD ["--tail-log"]