# ----------------------------- DESCRIPTION -----------------------------
# Slightly skinned down version of the official KASM Ubuntu Noble workspace dockerfile.
# Installs Ubuntu and gives root access to OS.
# Does NOT give DIND (Docker in a Docker).
#
# ----------------------------- INSTRUCTIONS -----------------------------
# In Dockerfile
# 1 - Decide if you are using the "1.18.0" or "develop" branch.
# 2 - When you build the dockerfile, be sure you specify the correct branch: squirrelworksllc/ubuntu-noble-dind:BRANCH-GOES-HERE
# In Workspace file following modification/update of THIS file:
# 1 - recalculate the docker size via commandline with one of the following (depending on docker tag used):
#     production: "docker inspect -f "{{ .Size }}" squirrelworksllc/ubuntu-noble-desktop:1.18.0"
#     development: "docker inspect -f "{{ .Size }}" squirrelworksllc/ubuntu-noble-desktop:develop"
# 2 - adjust the variable "uncompressed_size_mb"

# DEV NOTE: The tag can change as Kasm changes
ARG BASE_TAG="1.18.0-rolling-weekly"
# DEV NOTE: IF an Ubuntu version changes you should be making a new dockerfile!
ARG BASE_IMAGE="core-ubuntu-noble"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME=/home/kasm-default-profile
ENV STARTUPDIR=/dockerstartup
# If Chrome is being installed in the image, manually set to true. else set to false!
ENV INSTALL_CHROME=true
WORKDIR $HOME

### Envrionment config 
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/ubuntu/install/tools/install_tools.sh \
                  /ubuntu/install/chrome/install_chrome.sh \
                  /ubuntu/install/firefox/install_firefox.sh \
                  /ubuntu/install/thunderbird/install_thunderbird.sh \
                  /ubuntu/install/vs_code/install_vs_code.sh \
                  /ubuntu/install/remmina/install_remmina.sh \
                  /ubuntu/install/libre_office/install_libre_office.sh \
                  /ubuntu/install/signal/install_signal.sh \
                  /ubuntu/install/gimp/install_gimp.sh \
                  /ubuntu/install/ansible/install_ansible.sh \
                  /ubuntu/install/slack/install_slack.sh \
                  /ubuntu/install/discord/install_discord.sh \
                  /ubuntu/install/teams/install_teams.sh \
                  /ubuntu/install/obsidian/install_obsidian.sh \
                  /ubuntu/install/infosec_yara/install_infosec_yara.sh \
                  /ubuntu/install/tesseract_ocr/install_tesseract_ocr.sh \
                  /ubuntu/install/common/01_cleanup.sh"

# Copy install scripts
COPY ./src/ $INST_DIR

# Run installations
RUN set -eux; \
  apt-get update; \
  for SCRIPT in $INST_SCRIPTS; do \
    bash "${INST_DIR}${SCRIPT}"; \
  done; \
  "$STARTUPDIR/set_user_permission.sh" "$HOME"; \
  rm -f /etc/X11/xinit/Xclients; \
  chown 1000:0 "$HOME"; \
  mkdir -p /home/kasm-user; \
  chown -R 1000:0 /home/kasm-user; \
  rm -rf "${INST_DIR}"

# Userspace Runtime
ENV HOME=/home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]