# Custom script to create a Bitcurator5 Docker. Bitcurator 5's newest version supports up to Ubuntu Noble so
# this script will base the "root OS" off of the kasmweb ubuntu noble desktop weekly rolling.

# DEV NOTE: The tag can change as Kasm changes
ARG BASE_TAG="1.18.0-rolling-weekly"
# DEV NOTE: If Bitcurator is updated to use a newer LTS version, create a new dockerfile!
FROM kasmweb/core-ubuntu-noble:$BASE_TAG
USER root

ENV HOME=/home/kasm-default-profile
ENV STARTUPDIR=/dockerstartup
WORKDIR $HOME

### Envrionment config 
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/ubuntu/install/tools/install_tools_deluxe.sh \
                  /ubuntu/install/misc/install_tools.sh \
                  /ubuntu/install/bitcurator/install_bitcurator.sh \
                  /ubuntu/install/cleanup/cleanup.sh"

# Copy install scripts
COPY ./src/ $INST_DIR

# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done && \
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}

# Userspace Runtime
ENV HOME=/home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]

#TODO in Workspace file following modification/update of THIS file:
# 1 - recalculate the docker size via commandline with "docker inspect -f "{{ .Size }}" squirrelworksllc/bitcurator5:1.18.0"
# 2 - adjust the variable "uncompressed_size_mb"